### ISSUE TITLE
"No such file or directory: 'taiyaki/version.py'  when miniconda3/bin/python setup.py install

### ISSUE THREAD

**Issue by liujiazhe** [nanoporetech/taiyaki#1]
hello，
   I have a question and when I installed the software,there is a question that "No such file or directory: 'taiyaki/version.py'", and I don't know why. Could you please give me some suggestions?

**Comment by myrtlecat** [comment]
Thanks for pointing that out - it's a bug. We have made a [new release](https://github.com/nanoporetech/taiyaki/releases/tag/v3.0.1) that we hope will fix the issue.

Please can you try it out and less us know if you have the same problem?

**Comment by liujiazhe** [comment]
I have installed the new version successfully now ,and thank you!

**Comment by myrtlecat** [comment]
You're welcome, thanks for the feedback :-)
