### ISSUE TITLE
Guppy version?

### ISSUE THREAD

**Issue by dikkeaap** [nanoporetech/taiyaki#100]
Hi,

we have recently succesfully trained a model for a plant species sequenced on the MinION using R9.4 flowcell, and were able to supply that model to guppy 3.4.5 to perform basecalling. We have also sequenced the same plant species on the MinION on R10.3 flowcell and scussefully trained a model with those data. However, when running guppy with that model we get the following error:

```$ guppy_basecaller -i ../r10_min/raw/all/ -s basecalls_new -c /opt/ont/guppy/data/dna_r10.3_450bps_hac.cfg -m ../r10_min/model.json --device 'cuda:1 cuda:2'
ONT Guppy basecalling software version 3.4.5+fb1fbfb
config file:        /opt/ont/guppy/data/dna_r10.3_450bps_hac.cfg
model file:         ../r10_min/model.json
input path:         ../r10_min/raw/all/
save path:          basecalls_new
chunk size:         1000
chunks per runner:  512
records per file:   4000
num basecallers:    1
gpu device:         cuda:1 cuda:2
kernel path:        
runners per device: 4

[guppy/error] main: Unknown activation: swish
[guppy/warning] main: An error occurred in the basecaller. Aborting.
```

Is the model from Taiyaki incompatible with our guppy version? If so, which version of guppy would we need?

Alternatively, after reading https://github.com/nanoporetech/taiyaki#guppy-compatibility , do we need to adapt our training to be compatible with guppy?

**Comment by tmassingham-ont** [comment]
Hello.  The "swish" activation is a relative new feature in Guppy and you'll need version 3.6 or greater.
