### ISSUE TITLE
How to ouptut modified base with megalodon

### ISSUE THREAD

**Issue by organic-chemistry** [nanoporetech/taiyaki#101]
Hello I trained taiyaki on modified bases, an can use it successfully within taiyaki, and using --modified_base_output when basecalling.
However I cannot find the proper way to ouput the same information using megalodon. I can basecall with megalodon but do not find the right parameters to ouput the probability for the bases to be modified, or any information about it.
Is there a way?
Best!

**Comment by tmassingham-ont** [comment]
Hello.  This question is best addressed to the [Megalodon](https://github.com/nanoporetech/megalodon) project, could you open an issue there please?
