### ISSUE TITLE
Training a different architecture: ModuleNotFoundError: No module named 'netmodule'

### ISSUE THREAD

**Issue by organic-chemistry** [nanoporetech/taiyaki#102]
Hello,
I tried to modify one of your models and succedeed in training it, however I have trouble when using it for basecalling.
when I run :
`bin/basecall.py grouped_list_small_val/ ../taiyaki/normal_alphabet_batch_norm_peep/model_final.checkpoint  --device cuda:0 --output normal_alphabet_batch_norm_peep.fa`

I get the following error that I was not able to solve:
```
* Loading model.
Traceback (most recent call last):
  File "bin/basecall.py", line 273, in <module>
    main()
  File "bin/basecall.py", line 194, in main
    model = load_model(args.model).to(device)
  File "/home/jarbona/taiyaki/taiyaki/helpers.py", line 72, in load_model
    network = torch.load(model_file, map_location='cpu')
  File "/home/jarbona/anaconda3/envs/taiyaki/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/jarbona/anaconda3/envs/taiyaki/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'netmodule'
```
Is there a procedure to 'register' new models?
Thank you

**Comment by tmassingham-ont** [comment]
Hello.  Are you running the base caller in the same virtual environment in which you trained the model?  The error reported is that Python is unable to find a module (presumably a custom `netmodule.py` you've written).

**Comment by organic-chemistry** [comment]
Hello,
Yes it is in the same enviroment. 
I just tried to basecall in the same machine and enviroment after the training was done.

I have found a reference to a netmodule in the helpers.py file in the taiyaki directory:
```
def _load_python_model(model_file, **model_kwargs):
    netmodule = imp.load_source('netmodule', model_file)
    network = netmodule.network(**model_kwargs)
    return network
```
but this way of loading the module is used only when the module is a python file (as specified in the load_model function in the helpers.py file)

**Comment by tmassingham-ont** [comment]
Hello.   We think you may have defined functions in the original `model.py` file you used, which Taiyaki imports as `netmodule` during training.  As these are not present at base call time, an error results.
The easiest way to get base calling will be to modify `basecall.py` to create `netmodule` before the model checkpoint file is read.  Something like:  
```python
import imp
netmodule = imp.load_source('netmodule', 'model.py')
```

**Comment by organic-chemistry** [comment]
Ok, thank you it worked.
Maybe I should define my custom layers in the layers.py file.
Best.
