### ISSUE TITLE
Bug: naming modified bases with lowercase characters

### ISSUE THREAD

**Issue by marcpaga** [nanoporetech/taiyaki#103]
If in your references.fasta file you have annotated the modified bases with a lower case character, when reading the fasta file it will be converted to upper case. https://github.com/nanoporetech/taiyaki/blob/589863de71877418a446d083ffe2422d426dcc35/taiyaki/bio.py#L39-L59

If you then run something like (notice the lower case m for the 5mC):
`prepare_mapped_reads.py --jobs 32 --mod m C 5mC reads modbase.tsv modbase.hdf5 pretrained/r941_dna_minion.checkpoint modbase_references.fasta`

Then the alphabet will contain a `m` but the references will contain `M` which leads to a `True` comparison on line 53 (I think) of the linked code. Which then leads to an empty dictionary (if all your references have a an `m`). Thus failing any possible mapping since the reference sequence dictionary is empty.

Either `.toupper()` should be removed, but might have other consequences downstream; or a simpler and quick fix would be to raise an error if a lower case string is given for  the `--mod` argument.

**Comment by tmassingham-ont** [comment]
Thanks.  We'd fixed this in the in house version and it should be fixed in the version I've just released.
