### ISSUE TITLE
GPU accelerated prepare_mapped_reads.py?

### ISSUE THREAD

**Issue by Linkrw12** [nanoporetech/taiyaki#105]
I'm trying to run the taiyaki pipeline and got to the prepare_mapped_reads.py step, but even with 8 jobs running, it's taking over 90 hrs to generate and I had to terminate the process. Every other step completed relatively quickly. Here's my command below:
```
$ prepare_mapped_reads.py --jobs 8 {per_read_data.tsv}  {mapped_signal_file.hdf5} {model} {ref_per_read.fasta}
```
I know I can use the ```--limit``` flag and plan on incorporating it on the re-run, but almost feel like that's just wasted potential for the amount of data we could be training Guppy with. 

Does anyone know way to incorporate a GPU to accelerate the read preparation step? Is that even possible?

**Comment by SCDealy** [comment]
Are you sure it is actually using all 8 threads? When I was using prepare_mapped_reads.py a few months ago, it would launch all the processes, but only one or two would actually be active. I have some ideas as to why this might be the case, but haven't had time to investigate. As a work around I did a quick and dirty modification to significantly boost the value of "chunksize" in "bin/prepare_mapped_reads.py". A "chunksize" value of 1000 or more resulted in 100% use of all the allocated threads, though it took a while to get them all started (I was using a lot more than 8 threads). FWIW.

**Comment by Linkrw12** [comment]
Yeah, I checked htop to confirm that all threads were being used. I ended up using the ```--limit``` flag and ended up training only using a subsection of data. This still allowed me to train Guppy and get decent val loss, so I'm content. I could always play around with more flag options to incorporate more data, so I'll close the issue. Thank you for the response, @SCDealy
