### ISSUE TITLE
Does mGru_flipflop_model_r941_DNA.checkpoint exist?

### ISSUE THREAD

**Issue by Linkrw12** [nanoporetech/taiyaki#114]
I'm looking at the models dir and found the pretrained ```mLstm_flipflop_model_r941_DNA.checkpoint``` model. Does an equivalent exist for ```mGru_flipflop.py```?

**Comment by myrtlecat** [comment]
Closest equivalent using a GRU is `mGru_flipflop_remapping_model_r9_DNA.checkpoint`

**Comment by Linkrw12** [comment]
Oh, okay! I thought that was just for remapping when generating the training data. 

In that case, if I'm training the ```mLstm_flipflop_model_r941_DNA.checkpoint``` model, should I be using it to remap the training data as well? Or should I consistently stick with ```mGru_flipflop_remapping_model_r9_DNA.checkpoint``` when generating training data?

**Comment by myrtlecat** [comment]
Either should work just fine.

**Comment by Linkrw12** [comment]
Perfect! Thank you so much @myrtlecat, You're a life saver!
