### ISSUE TITLE
Make Install on GPU

### ISSUE THREAD

**Issue by fneuh** [nanoporetech/taiyaki#16]
Hi,
I am trying to install taiyaki on GPU using 'make install'. Using python 3.5.2 and cuda 9.0, I get the following error:

building 'taiyaki.squiggle_match.squiggle_match' extension
/apps/well/gcc/5.4.0/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./taiyaki/squiggle_match -I/gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/numpy/core/include -I/apps/well/python/3.5.2-gcc5.4.0/include/python3.5m -c taiyaki/squiggle_match/squiggle_match.c -o build/temp.linux-x86_64-3.5/taiyaki/squiggle_match/squiggle_match.o -O3 -fopenmp -std=c99 -march=native
In file included from /gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from taiyaki/squiggle_match/squiggle_match.c:626:
/gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
/tmp/ccqWrNNb.s: Assembler messages:
/tmp/ccqWrNNb.s:8517: Error: no such instruction: `shlx %rax,%rdi,%rdx'
error: command '/apps/well/gcc/5.4.0/bin/gcc' failed with exit status 1
make: *** [install] Error 1

So far I haven't found a solution for this, do you have an idea for this issue?

Thanks,
Florian

**Comment by myrtlecat** [comment]
It seems that your compiler (`gcc`) is producing instructions that your assembler (probably `/usr/bin/as`) does not recognise. Perhaps your assembler is older than the CPU architecture? The instruction causing the error (`shlx`) was introduced in intel chips around 2013 and in AMD chips in 2015, so versions of `as` from before then won't support it.

To help us get to the bottom of it, and to help anyone else experiencing similar issues, could you please provide the following information:

- `gcc` version
- `as` version
- Operation system type and version (Is it CentOS 6 by any chance?!)
- CPU architecture

This might be hard for us to reproduce, but some suggestions that hopefully will help:

- Upgrade `as`
- Downgrade `gcc`
- Modify the flags in setup.py ([here](https://github.com/nanoporetech/taiyaki/blob/c34b83c30182034fe6f598352e184eb94f87a0bf/setup.py#L36) and [here](https://github.com/nanoporetech/taiyaki/blob/c34b83c30182034fe6f598352e184eb94f87a0bf/setup.py#L42)) to avoid using Haswell-specific instructions (try removing `-march=native` perhaps?)

**Comment by fneuh** [comment]
The information you requested:
```
$ as -version
GNU assembler version 2.25.1-22.base.el7
This assembler was configured for a target of `x86_64-redhat-linux'
```

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
```
I removed `-march=native` at the two specified sites, 'make install' now finishes without an error, but when I run the workflow test (make workflow), I get the following error:

```
Traceback (most recent call last):
  File "/well/ont/apps/taiyaki_gpu/taiyaki/bin/get_refs_from_sam.py", line 9, in <module>
    from taiyaki.helpers import fasta_file_to_dict, open_file_or_stdout
  File "/gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/taiyaki/helpers.py", line 9, in <module>
    import torch
  File "/gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /gpfs1/well/ont/apps/taiyaki_gpu/taiyaki/venv/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)
make[1]: *** [/well/ont/apps/taiyaki_gpu/taiyaki/RESULTS/training_ingredients/per_read_references_from_sam.fa] Error 1
make[1]: Leaving directory `/gpfs1/well/ont/apps/taiyaki_gpu/taiyaki'
make: *** [workflow] Error 2
```
For up- or downgrading as/ gcc I have to check back to system administration, to see if that is an option.

**Comment by myrtlecat** [comment]
Glad the changes to `setup.py` helped. In that case, I think it's probably best to leave `gcc` and `as` alone as there might be unintended consequences. We will investigate whether we can drop the `-march=native` flag.

The new error is originating from pytorch, not from taiyaki, so you are more likely to find the solution by posting on the pytorch forums or github. The problems sounds similar to those reported [here](https://github.com/pytorch/pytorch/issues/6607) and [here](https://github.com/pytorch/pytorch/issues/14274) and your favourite search engine will probably throw up more. I hope one of those links helps.

**Comment by fneuh** [comment]
I eventually moved to another GPU node, where the installation worked out fine. So I did not need to solve the issue I was having with pytorch. 

Thanks very much for the help!
