### ISSUE TITLE
Does taiyaki support 5th and 6th base training?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/taiyaki#2]
If we want to have a basecaller that calls 5 bases or 6 bases, can we use taiyaki to train a model then supply to the basecaller?

**Comment by tmassingham-ont** [comment]
These features, along with a base caller, will be released soon.

**Comment by avilella** [comment]
Has this been included in today's release? Is it in the cards any time soon? Thanks in advance and apologies for the constant insisting: we are really keen on trying this out.

**Comment by tmassingham-ont** [comment]
Not in this release, but we have finalising the modified base merge and are currently testing.

**Comment by avilella** [comment]
Great, thanks for the update. Looking forward to it.
