### ISSUE TITLE
prepare_mapped_reads.py fails to produce remapping on GPU while it works just fine on CPU

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/taiyaki#21]
Hi, `prepare_mapped_reads.py` fails to produce remapping on GPU while it works just fine on CPU. I'm training RNA models for detection of modifications using `pretrained/r941_rna_minion.checkpoint`. Any idea? 

```
prepare_mapped_reads.py --device cuda:0 --jobs 4 --alphabet ACGU ... modbase.hdf5
* 18150 reads failed to produce remapping results due to: Failure applying basecall network to remap read.

prepare_mapped_reads.py --jobs 4 --alphabet ACGU ... modbase_cpu.hdf5
..................................................      50
...
..................................................   18150

ll *.hdf5
-rwxr-xr-x 1 lpryszcz lpryszcz 4.3G May 29 23:25 mapped_reads_cpu.hdf5*
-rwxr-xr-x 1 lpryszcz lpryszcz 6.1K May 29 19:44 mapped_reads.hdf5*
```

**Comment by myrtlecat** [comment]
Not sure exactly what has gone wrong there. However, we would not recommend using the GPU to complete the `prepare_mapped_reads.py` step, and we intend to disable this option in the next release. Using the GPU for this step doesn't really save you anything (it doesn't finish quicker and RAM and CPU requirements remain about the same), and it is possible for an error in one thread to put the device into an unrecoverable state causing all reads to fail.

**Comment by lpryszcz** [comment]
Thanks @myrtlecat , understood!
