### ISSUE TITLE
Model trained on in vitro transcribed RNA works well on test set, but not on RNA isolated from cells

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/taiyaki#29]
Hi, could you please clarify what `--winlen` mean? Does it mean windows of 19 bases are used for training (and thus later for basecalling)? 

`  --winlen WINLEN       Length of window over data (default: 19)`

I'm asking, because I've trained a model for RNA using _in vitro_ transcribed RNA molecules (IVT) that cover all possible 5-mers. The model works great both, on the training and test set (Fig1), but it doesn't work on RNA isolated from cells (Fig2), while default guppy3 model works just fine (Fig3). 
Would setting `--winlen 5` (thus training to detect 5-mers) solve the issue?

**Fig1: In vitro transcribed sample [guppy3 using model trained on IVT]**
![image](https://user-images.githubusercontent.com/988152/60093672-59b63c00-974a-11e9-890e-9624f308173d.png)

**Fig2: Biological sample [guppy3 using model trained on IVT]**
![image](https://user-images.githubusercontent.com/988152/60093487-db599a00-9749-11e9-9841-4bc1635bc49d.png)

**Fig3: Biological sample [guppy3 with default model]**
![image](https://user-images.githubusercontent.com/988152/60093632-35f2f600-974a-11e9-9645-b55e8d8b4dbb.png)

In addition, could you please briefly describe also how chunks.hdf5 was generated for _ab inito_ training? That would be very useful in the near future!

**Comment by gitty-gaurav** [comment]
Hi @lpryszcz , 
I am curious to know the cause behind this issue. Why does guppy3 using model trained on IVT leads to low percent identity? Can tuning '--mod_factor' parameter help resolve this issue? I will be glad to know if you have already found the reason/solution. Thanks

Best, Gaurav

**Comment by callumparr** [comment]
May I ask did you see similar result using the python basecall.py script? I've seen very good performance with the latter but completely different results with guppy 3.2.2
