### ISSUE TITLE
Only two kinds of nucleotides predicted by GUPPY on RNA model just trained

### ISSUE THREAD

**Issue by weir12** [nanoporetech/taiyaki#35]
Hi:
I have encountered an similar but different issue with https://github.com/nanoporetech/taiyaki/issues/23#issue-451404363. 
In my condition,Only two kinds of nucleotides (UC) are predicted in all reads.like this:
```
@b706192c-74b0-4c84-809a-1787d3b566ba runid=5bf02a9de9e0ebfa894230c4ecc621d657cfbace sampleid=20190522-NPL0934-K2 read=14611 ch=107 start_time=2019-05-22T09:20:10Z
UCUUCGCUCUUCUCUCUCUCUCUCCUCUCUCUUCUCCU
+
#$$$%"%#%#$%$%#&"%%%$%$%%#$$&$%$#%$%$&
@2a7ead7c-de5f-4d2c-99bd-bd2b77f146c8 runid=5bf02a9de9e0ebfa894230c4ecc621d657cfbace sampleid=20190522-NPL0934-K2 read=16910 ch=261 start_time=2019-05-22T10:08:50Z
UCUCUCUCUUUCUCUCUUUUCUCUCUCUCUCCU
+
$%$%#%#$#$#%$%$%$###&$%$%$%#&$''$
@8b60657e-e05e-454f-89a6-a36511a78926 runid=5bf02a9de9e0ebfa894230c4ecc621d657cfbace sampleid=20190522-NPL0934-K2 read=1551 ch=266 start_time=2019-05-22T02:43:14Z
UUCCUCUUUUCUCUCU
+
$#%%#&##$#$$%#$&
@b7adb84b-e918-47ab-8ac8-a1d15944eb3e runid=5bf02a9de9e0ebfa894230c4ecc621d657cfbace sampleid=20190522-NPL0934-K2 read=27890 ch=478 start_time=2019-05-22T19:10:28Z
UCUCUUCUCUCUCUCCCGCCUCUCUCU
``` 
I've also trained the model following your guide.Apparently,the length of reads also is abnormal.

**Comment by tmassingham-ont** [comment]
What is the final loss that your model achieved?  This should be recorded in the `model.log` file in the training directory.

Looking at your previous issue #32, there may well have problems with your training set.  Are you able to give more details about what you are training from and what you are trying to achieve?

**Comment by weir12** [comment]
@tmassingham-ont 
Thanks your for your support ! I seem to have solved the problem by reversing` reference files` . Maybe you should add few tips about extra steps of RNA sample to the modbase doc.

**Comment by tmassingham-ont** [comment]
Will do, thank you.
