### ISSUE TITLE
prepare_reads script running very slowly 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#42]
I am running this on around 300, 000 direct RNA reads with 100% replacement with modified U. 

Running with --jobs 12 (The maximum I can dot) but based on the progress this would take forever. I am unsure how much this will go faster using more threads.

Running htop there only seems to be 4 jobs running at any one time. RAM is not maxed out. 

Some warning is printed may be reason running slowly

`/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'taiyaki.layers.Serial' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'taiyaki.layers.Convolution' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'taiyaki.layers.GruMod' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'taiyaki.layers.GlobalNormFlipFlop' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)`

**Comment by tmassingham-ont** [comment]
The warnings won't affect the run time, I'm afraid it is just slow at the moment.  Work is in progress to speed it up but for now the options are to use fewer reads (say 10k to 30k) or split over many computers and then merge using `merge_mappedsignalfiles.py`.

**Comment by callumparr** [comment]
Thank you. This is good workaround. I will give this a go.
