### ISSUE TITLE
Training modified RNA model

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#45]
I am working through the walkthrough and comments in the issue section here to train model on IVT synthesized mRNA with 100% replacement with modified U. I also have data set with unmodified mRNA.

**General**
Should I mix these two data sets together (completely modified reads, with unmodified reads)? Or just training on the modified reads.  Intermediate models provided already know context of canonical U but if ab initio I guess I need to provide signal from canonical U?

**Specifically**
The two steps of the train_mod for RNA which intermediate model should I start with?

1) mGru_mod_cat_flipflop for the first 1st step
2) an ab initio model trained on mixture of modified and unmodified reads

If using mGru_mod_cat_flipflop should I add these flags mentioned in this issue previous because this model is used to train for DNA not RNA?

https://github.com/nanoporetech/taiyaki/issues/32#issuecomment-517638751 

Should I do this in the first part of the training ?

**Comment by marcus1487** [comment]
The answers to these questions relies mostly on the goal for the trained model.

As a first point of clarification, the `mGru_mod_cat_flipflop.py` model allows for the specific detection of modified bases whereas the `mGru_flipflop.py` model will call only canonical bases. Note that given appropriate training data the standard `mGru_flipflop.py` model can be trained to collapse modified bases to a desired canonical base.

Thus if the desired output is the specific detection of modified bases, then training should start from the `mGru_mod_cat_flipflop.py` model file. If the goal is to collapse modified bases to a desired canonical base, then training should begin with the standard `mGru_flipflop.py` model file.

Thus, this decision is independent of the entry point for training (either ab initio or full strand training). The standard or `mod_cat` model must be specified for either entry point. The purpose of the ab initio training is discussed more in the [docs](https://github.com/nanoporetech/taiyaki/blob/master/docs/abinitio.rst). Note that at the moment the ab initio training script is not currently compatible with the modified base model type, though this is a goal for future development.

The decision as to whether to combine the two data sets for training again relies on the goals for the trained model. If the model should be able to accurately base call canonical bases, then merging in the canonical data set would help this model toward this goal. If on the other hand the model will only be used to accurately base call strands composed of the modified base, then training from only the modified strands would be sufficient. Keep in mind that at the outset of training the models do not have any preference to identify canonical bases. This is only learned through training the model from the provided training data.

The final question is more simple. The parameters mentioned in the linked issue (#32) should be used from the outset of training. Once model training has started (as with the `mod_cat` model decision) these parameters cannot be changed.

At a higher level, training from a sample containing completely modified bases may not perform as desired in contexts outside of the training data type. To be more specific, if this model is tested against a sample with this modified base in isolation (or observed relatively sparsely) performance may be quite poor as the model was never trained with examples of this modification in isolation. This is not to say that obtaining a high confidence data set with modified bases introduced relatively sparsely is a simple task, but given this input data type expectations for performance outside of the training data type should be tempered appropriately.

**Comment by callumparr** [comment]
Thank you for the explanation. I am understand better now.
