### ISSUE TITLE
Guppy can't run on GPU with trained model

### ISSUE THREAD

**Issue by amir-azizi** [nanoporetech/taiyaki#46]
Hi, 
I trained Taiyaki (4.1.0) to detect m6A mods in RNA and converted the model into json (with bin/dump_json.py).
I can only use Guppy3.2.2 (1) on this trained model in CPU mode and get the following error in GPU mode:
`[guppy/error] main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:146: ')
[guppy/warning] main: An error occurred in the basecaller. Aborting.`

Guppy runs on GPU fine when used on it's default model.
Any ideas what can be the problem?

1. `guppy_basecaller --qscore_filtering --compress_fastq --fast5_out -r -i ${1} -s ${2} --flowcell FLO-MIN106 --kit SQK-RNA002 --model path_to_model/model.json --num_callers 4 --gpu_runners_per_device 3 --device "cuda:all"`

**Comment by callumparr** [comment]
Did you try running it with basecall.py script first to see if it all works? This can use CPU and GPU device. May help to determine if issue with your model or model fitting in with guppy

**Comment by amir-azizi** [comment]
It works with `basecall.py`, however much like https://github.com/nanoporetech/taiyaki/issues/38, the called sequences are different from the reference ones. 

I wanted to check if I get similar results in Guppy.

Thanks.

**Comment by iiSeymour** [comment]
@amir-azizi is it possible that one or more of the GPUs already has all its memory allocated? You can use `nvidia-smi` to find out? Can you try running on a single GPU with `--device cuda:0` *(assuming device 0 has enough memory)*.

**Comment by amir-azizi** [comment]
All 4 GPUs in the node are free. These are Tesla P4 machines with 8GB RAM.
It also fails when I run with on single device, but the error is different:

`[guppy/error] main: Could not create CUDA device 0: basic_string::_S_construct NULL not valid
[guppy/warning] main: An error occurred in the basecaller. Aborting.`

Thanks

**Comment by iiSeymour** [comment]
I suspect it's trying to allocate more than 8GB per card. Can you try with `--gpu_runners_per_device 1`, `--num_callers 1` and `--chunks_per_runner 1`.

**Comment by amir-azizi** [comment]
I tried with these flags, but still got the same error.

**Comment by iiSeymour** [comment]
As `basecall.py` is working it appears to be purely a guppy issue, can you start a thread in the community and share the model there?

**Comment by amir-azizi** [comment]
Thank you @iiSeymour. I don't have access to the community yet. I asked a colleague of mine in the group to do that.

**Comment by callumparr** [comment]
I don’t know if possible but this is from guppy protocol page and instead of playing around with runners you can tell how much memory to limit to e.g cuda:0:7G” or cuda:0:75% to give some buffer? 

Although running out memory brings up different error from experience

**Comment by tjakobi** [comment]
The issue seems to be related to the environment. Loading the CUDA environment (10.1) and adding libraries to the `LD_LIBRARY_PATH` seems to cause this issue. When unloading the CUDA environment, basecalling starts as expected.

**Comment by iiSeymour** [comment]
:+1:

**Comment by zmunro** [comment]
@tjakobi Can you explain what you mean by "unloading the CUDA environment"?
I am currently running guppy on a few VMs at once (each with 1 nvidia P100 GPU) for long periods of time, and every once in awhile I will come back and see that I am getting an error similar to what you mentioned: 
```
main: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:185: CUDA_ERROR_UNKNOWN
```
Technically they are running in pods in kubernetes, and they get restarted every once in awhile since the machines they are running on are preemptible. 

I have the `LD_LIBRARY_PATH` set to `/usr/local/nvidia/lib64:/usr/local/nvidia/bin`
Here is the full dockerfile I am using: [https://pastebin.com/qtQd0b46](https://pastebin.com/qtQd0b46)

**Comment by tjakobi** [comment]
Dear @zmunro,

we are using the `module environment` on our cluster to load specific software packages. 

Unloading the module in this case refers to removing any reference to the CUDA SDK itself in the LD_LIBRARY_PATH or the include path. 

Loading the CUDA SDK environment first and loading guppy afterwards did not work for us. Only without the CUDA SDK loaded, guppy would run.

Cheers
Tobias

**Comment by zhanxw** [comment]
I can replicate the problem by @tjakobi .

The root reason is that in the `module environment`, the environment variable `CUDA_VISIBLE_DEVICES` was set to `NoDevice`. Then guppy won't find the GPU and crashed. 

My solution is to add `unset CUDA_VISIBLE_DEVICES` in your script.
