### ISSUE TITLE
train_mod: RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#49]
Trying to run train_mod on a HPC with GPU installed but get error similar to #37 

environment

`Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-75-generic x86_64)`

syst.admin install Taiyaki system wide with the setup.py file and creating a virtual environment. 

```
(python3) (base) callum@dgt-gpu1:~$ source taiyaki/venv/bin/activate
-bash: taiyaki/venv/bin/activate: No such file or directory
(python3) (base) callum@dgt-gpu1:~$ python -c 'import taiyaki; print(taiyaki.__version__)'
4.1.0
(python3) (base) callum@dgt-gpu1:~$ python -c 'import torch; print(torch.__version__)'
1.0.0
(python3) (base) callum@dgt-gpu1:~$ python -c 'import torch; print(torch.version.cuda)'
9.0.176
(python3) (base) callum@dgt-gpu1:~$ python -c 'import torch; print(torch.backends.cudnn.version())'
7401
(python3) (base) callum@dgt-gpu1:~$ python -c 'import torch; print(torch.backends.cudnn.enabled)'
True
```

Run 

After activating environment 

`(python3) (base) callum@dgt-gpu1:~$ train_mod_flipflop.py --device cuda:0 --mod_factor 0.01 --outdir taiyaki/taiyaki_modbase/training_1 taiyaki/models/mGru_cat_mod_flipflop.py taiyaki/taiyaki_modbase/intermediate_files/modbase.hdf5 --overwrite`

error traceback 

```
* Taiyaki version 4.1.0
* Command line
/usr/local/python3/bin/train_mod_flipflop.py --device cuda:0 --mod_factor 0.01 --outdir taiyaki/taiyaki_modbase/training_1 taiyaki/models/mGru_cat_mod_flipflop.py taiyaki/taiyaki_modbase/intermediate_files/modbase.hdf5 --overwrite
* Loading data from taiyaki/taiyaki_modbase/intermediate_files/modbase.hdf5
* Per read file MD5 ffd4296fb9fce0b45ad0230c2f8936cb
* Will train from all strands
* Loaded 5891 reads.
* Using alphabet definition: canonical alphabet ACGT with modified base(s) Y=6mA (alt to A), Z=5mC (alt to C)
* Sampled 1000 chunks: median(mean_dwell)=9.90, mad(mean_dwell)=0.87
* Reading network from taiyaki/models/mGru_cat_mod_flipflop.py
Traceback (most recent call last):
  File "/usr/local/python3/bin/train_mod_flipflop.py", line 4, in <module>
    __import__('pkg_resources').run_script('taiyaki==4.1.0', 'train_mod_flipflop.py')
  File "/usr/local/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/python3/lib/python3.5/site-packages/taiyaki-4.1.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/train_mod_flipflop.py", line 358, in <module>
    main()
  File "/usr/local/python3/lib/python3.5/site-packages/taiyaki-4.1.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/train_mod_flipflop.py", line 202, in main
    network = helpers.load_model(args.model, **model_kwargs).to(device)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/usr/local/python3/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

sys.admin tried upgrade and downgrading torch package and CUDA to 10.0.130 but still provides same error: 

`make tests` `make acctest` and `make unittest` do pass but 2 were skipped 

`../../test/unit/test_layers.py::ANNTest::test_017_decode_simple SKIPPED`
`../../test/unit/test_layers.py::GlobalNormFlipFlopTest::test_cupy_and_non_cupy_same SKIPPED`

I am unsure if this relates.

I managed to install and run train_mod on another local station installed within a docker container running ubuntu 16.04 and also with same dependency versions. How I installed with `git clone`, and then `make install` not using setup.py 

sys.admin advised me there may be some bug in setup.py file:

> taiyaki/setup.py ( by git clone) has a bug. ( package_data line)
>  diff is

```
(taiyaki) anon@dgt-gpu1:~/src/taiyaki$ diff -u setup.py.orig setup.py
--- setup.py.orig	2019-08-23 11:04:56.570220292 +0900
+++ setup.py	2019-08-23 11:07:25.946714589 +0900
@@ -73,7 +73,7 @@
     ],
 
     packages=find_packages(exclude=["*.test", "*.test.*", "test.*", "test", "bin"]),
-    package_data={'configs': 'data/configs/*'},
+    package_data={'configs': ['data/configs/*']},
     exclude_package_data={'': ['*.hdf', '*.c', '*.h']},
     ext_modules=extensions,
     setup_requires=["pytest-runner", "pytest-xdist"],
```

**Comment by myrtlecat** [comment]
The bug in `ssetup.py` only occurs with the very latest version of `setuptools` (version 41.1.0 released last week) and it will hit during taiyaki installation, so if the installation appeared to go correctly then this bug isn't affecting you.

The problem appears to be with your CUDA set-up.

You mentioned CUDA 10, but the printout you provided shows that you have the CUDA 9 version of pytorch installed. There is a different pytorch package for each major CUDA release. Can you please confirm that your torch and CUDA versions match correctly?

CUDA version:
`nvcc --version`

CUDA version used to build your torch package:
`python -c 'import torch; print(torch.version.cuda)'`

If these do not show the same version then you will have to attempt to resinstall taiyaki with the correct pytorch package.

**Comment by callumparr** [comment]
> You mentioned CUDA 10, but the printout you provided shows that you have the CUDA 9 version of pytorch installed. There is a different pytorch package for each major CUDA release. Can you please confirm that your torch and CUDA versions match correctly?

Sorry I meant to put that we originally started with CUDA 9 with torch v1.0.1. Then tried going up to CUDA 10.0.130 but still had issues so went back to the original CUDA 9. 

> CUDA version:
> `nvcc --version`
> 
> CUDA version used to build your torch package:
> `python -c 'import torch; print(torch.version.cuda)'`
> 
> If these do not show the same version then you will have to attempt to resinstall taiyaki with the correct pytorch package.

```
(python3) (base) callum@dgt-gpu1:~$ python -c 'import torch; print(torch.version.cuda)'
9.0.176
(python3) (base) callum@dgt-gpu1:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

Ah OK installed CUDA version is 10.1.

torch compatible with CUDA 10.1 I believe is not compatible with Taiyaki ? In this case I should install CUDA 10.0.130 and then try to reinstall Taiyaki? This will install correct torch compatible with taiyaki?

**Comment by myrtlecat** [comment]
>  In this case I should install CUDA 10.0.130 and then try to reinstall Taiyaki? This will install correct torch compatible with taiyaki?

Yes, that should work. If you are installing from a git clone you can run `make show_cuda_version` (before running `make install`) to check what CUDA versions is detected and check that correct versions of pytorch and cupy will be installed.
