### ISSUE TITLE
guppy 3.2.2 --fast_out for modifications with custom model for RNA 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#51]
According to the guppy devs, mod-bases should already be working with guppy 3.1. If you use the `--fast5_out` option, guppy will write modification probabilities back to the fast5s that you basecalled. There aren't any tools yet, so you will have to extract this information yourself using hdf5 or h5py. You are looking for a dataset called `ModBaseProbs`. Please open another issue if you need more help with guppy's mod-bases output.

_Originally posted by @myrtlecat in https://github.com/nanoporetech/taiyaki/issues/26#issuecomment-501310444_

I've generate a model for RNA modification of my choice. I am having issues with basecall.py script running out of memory when encounters large read. If I were to dump the model to json file for guppy, will the fast5_out record these probabilities? Or is still only for DNA m5C and m6A?

**Comment by tmassingham-ont** [comment]
The implementation for modified bases in Guppy should be generic, the restriction to 5mC and 6mA being in the models we provide.  Converting to a json and running in Guppy should work, let us know how you get on.

**Comment by callumparr** [comment]
thank you
