### ISSUE TITLE
guppy with new model trained on modified uridine RNA outputs high identities but low basecall quality 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#53]
I have a similar yet opposite problem to this previous issue https://github.com/nanoporetech/taiyaki/issues/26#issue-454223766

Where I have a model that works well with the basecall.py script but when dumped to model file for guppy, the output basecalls seem to still have very low basecall quality despite using reads that were originally filtered to pass the min_qscore >7. Despite this the basecall reads both fail and pass map well (identities well over 95%).

I read that for RNA, increasing chunk size to 1200 may help but this only very marginally. 

Only thing I can assume is guppy assumes RNA to use AGCU alphabet and require additional step to output T where as I used AGCT alphabet to train my model. 

Below is percent identity vs length output from mapped reads outputted from basecall.py and guppy.  I show output on the input trained data to illustrate the point that guppy outputs lower basecall qualities than the input data. This data is a mixture of unmodified and modified reads.

output from basecall.py looks solid, of course because this is the data used to train:
 
<img width="775" alt="Screen Shot 2019-09-26 at 3 27 45 PM" src="https://user-images.githubusercontent.com/41637575/65697106-44ff8200-e072-11e9-9e62-4eadf512fa32.png">

output from guppy using the trained model and rna941_hac.cfg: 

<img width="888" alt="Screen Shot 2019-09-26 at 4 08 24 PM" src="https://user-images.githubusercontent.com/41637575/65700683-f654e680-e077-11e9-93d2-0bea075caf14.png">

Here is pycoQC of the sequencing summary file , around 2/3 of reads are classified as 'fail'

using new trained model for basecall

<img width="976" alt="Screen Shot 2019-09-26 at 4 11 36 PM" src="https://user-images.githubusercontent.com/41637575/65701161-bf330500-e078-11e9-95f8-a2554f0a6391.png">

using the standard RNA hac model with guppy 

<img width="948" alt="Screen Shot 2019-09-26 at 4 12 25 PM" src="https://user-images.githubusercontent.com/41637575/65701186-c9550380-e078-11e9-94c4-eb9252e6f2c5.png">

To generate this model

1. I took reads generated from IVT mRNA with or without modified uridine. I filtered out raw fast5 reads that generated passed reads from guppy and greater than 500nt as I think the IVT generates can produce plenty of premature termination transcripts. I output fastq sequences with T instead of U

1. Then generated a reference fasta for each of the reads. For the modified reads, I converted T to Y for the modification. For all reads are reversed the sequence to match with the physical mRNA molecule passing through the pore

1. I generated the prepare mapped reads hdf5 files separately for unmodified and modified and then later merged them with the merge.py script. Resquiggle used the pretrained/r941_rna_minion.checkpoint file given in the taiyaki_modbase walkthrough. Using AGCT alphabet as I output T originally with guppy. 

1. Then trained data using the taiyaki/models/mGru_cat_mod_flipflop.py for first round and using AGCT and additionally parameters --winlen 31, --size 256, --stride 10 to make compatible with RNA hac. 

Far as I can tell things went smoothly for training. Although for mapped squiggle to sequence it doesn't look as clean as DNA examples but this probably has something to do with the DNA adaptor at 3' end of RNA molecule and the polyA on the raw read but absent form the basecalled sequence.

**Comment by weir12** [comment]
I have a question,for the RNA sample, should the alphabet be '**ACGT**' or '**ACGU**'?

**Comment by callumparr** [comment]
> I have a question,for the RNA sample, should the alphabet be '**ACGT**' or '**ACGU**'?

From my understanding, in essence you can choose so long as its maintained through the initial base calling with guppy, Resquiggle, and then training.

I am unsure what guppy is doing underneath as the RNA config files defaults to convert U to T unless you turn it off with the `--u_substitution false`. Thats why I think there may be conflict with my model being used with any RNA config file for guppy. 

In principle its probably best to stick to ACGU for RNA. 

Did you notice any low base call qualities output by guppy with your ACGU alphabet model?

**Comment by callumparr** [comment]
This is the output of mapped signal and output of training 1 and 2 

<img width="1195" alt="Screen Shot 2019-09-27 at 5 05 22 AM" src="https://user-images.githubusercontent.com/41637575/65741598-7ca71200-e0e4-11e9-81f6-8ef8713fc4b5.png">

<img width="639" alt="Screen Shot 2019-09-27 at 5 10 20 AM" src="https://user-images.githubusercontent.com/41637575/65741862-9dbc3280-e0e5-11e9-97dd-981c9547ffcb.png">

<img width="638" alt="Screen Shot 2019-09-27 at 5 10 46 AM" src="https://user-images.githubusercontent.com/41637575/65741969-086d6e00-e0e6-11e9-89af-48c5e3f8b5c6.png">

**Comment by myrtlecat** [comment]
The choice between ACGT and ACGU should not matter, as long as the alphabet used for `prepare_mapped_reads.py` is consistent with the per-read references you provide (i.e. if you use Ts in the references then use `ACGT`).

The accuracy of the basecalls is much better than the Q-scores imply, which indicates a problem with the calibration of the Q-scores. We don't calculate Q-scores in taiyaki, this is only done in guppy, so I'm afraid I don't know exactly why this could happen.

I note however that guppy applies a shift and scale to the Q-scores, and these seem to be different for each model. If you ask on the community you may get an answer from the guppy devs about how these are determined. In the meantime you can adjust these with the command line arguments for guppy: `--qscore_offset` and `--qscore_scale`, or you can adjust the pass/fail cutoff with `--min_qscore`.

**Comment by Wildstrubu** [comment]
Hi @callumparr 

Did the U to T substitution help in the end?

Thanks a lot for describing your workflow above. I am working as well with IVT RNA (U or modified U) and I would like to train guppy to recognize the modified U as canonical U/T. I struggle with creating the reference files for the reads. Would you be open for sharing your detailed protocol?

At the moment I do the following steps.

guppy_basecaller -i ~fast5/ --config rna_r9.4.1_70bps_hac.cfg --reverse_sequence 1  --min_qscore 7 --calib_detect 1
minimap2 -ax splice -uf -k14 ~/RNA_reference.fasta ~/*.fastq > ~/reads.sam
# convert all T to Y and modify to a file = >ID and sequence below --> save as read_referencs.fasta
generate_per_read_params.py --jobs 32 ~/fast5/ > read_params.tsv
prepare_mapped_reads.py  --jobs 32 ~/fast5/ read_params.tsv mapped_reads.hdf5  pretrained/r941_rna_minion.checkpoint read_references.fasta
train_flipflop.py --size 256 --stride 10 --winlen 31 --device 1 --mod_factor 0.01 --outdir ~/output/training1/ ~/taiyaki/models/mGru_flipflop.py mapped_reads.hdf5
train_flipflop.py --size 256 --stride 10 --winlen 31 --device 1 --mod_factor 1.0 --outdir ~/output/  ~/training1/model_final.checkpoint mapped_reads.hdf5

#Export and run guppy
dump_json.py training/model_final.checkpoint > model.json
guppy_basecaller -i reads -s basecalls_new -c /opt/ont/guppy/data/rna_r9.4.1_70bps_hac.cfg -m /model.json --device cuda:0 --reverse_sequence 1 --u_subsitution 1 --min_qscore 7 --calib_detect 1

Many thanks in advance for your inputs!

**Comment by callumparr** [comment]
After some further reading the U:T substitution was the not problem but rather the scaling factors that guppy requires to calibrate suitable basecall qualities (i.e. to give fastq format instead of fasta). Since I posted this there has been an update of taiyak that generates a scaling factor but I have not actually gone back and redone this. I kind of lost track with it all.

**Comment by Wildstrubu** [comment]
@callumparr Thanks for your prompt feedback!

How did you create the file with the reference for each read?

**Comment by callumparr** [comment]
> @callumparr Thanks for your prompt feedback!
> 
> How did you create the file with the reference for each read?

Sorry I keep pressing ctrl return before finishing the reply. Please see above.

**Comment by Wildstrubu** [comment]
Your explanation are all very helpful!

Yes, its 100% IVT RNA where all U are modified and I don't care of finding the position where the modification is, but rather having a correct basecalling when performing guppy. 

bin/get_refs_from_sam.py <genomic references fasta> <one or more SAM/BAM files> --output 
<name of output reference_fasta>

Creating the <one or more SAM/BAM files> is for me difficult to follow. As guppy is not calling the ground truth of the bases correct in the first place as its a non-trained model. You are saying, that I don't have to use the actual guppy output. What then?

Thanks!

**Comment by callumparr** [comment]
Ah OK I follow you. So depending on the % of modified rNTP replacement you would expect that the basecall quality to be way off so you are kinda restricted in the number of reads you can use. 

You have to use the guppy output pass reads that you can get (even if this 30% of the original total read number). You should still be able to map these reads, although they, of course, will have many 'mutations' relative to unmodified UTP mRNA.  Minimap2 will still give you something to work with, i.e. the start and endpoint of mapped read that is extracted by `get_refs_from_sam.py`

The rest of the training will then get you to a point where you can rebasecall your test set. 

Based on your reply I think you can follow the normal walthrough.rst instead of generating a modbase model. But if you do want to generate a mod base model, there is something I forgot. 

If you generated reads with 100% modified UTP you also need to provide the training with some unmodified reads as well, otherwise it will never learn what a canonical UTP raw signal look like. So you need to in parallel generate some read chunks and a match reference sequence but of course **not** substituting T for Y. You can then combine the reads together in a single directory and proceed with the following steps. For simplicity I did 50:50 (reads w/ 100% mod rUTP: reads w/ rUTP). You can imagine that this whole process may be biased as the unmodified reads will be a more broad dataset because it has no issues with being mapped. Perhaps you can do this to generate a model that you can later use for a second round of training on new data, like an intermediate. 

Make sure to partition any useable FASTQ data from the beginning, so you have some to test your brand spanking new model on. I may have got too excited and not realised this until the end and had to start again.

**Comment by Wildstrubu** [comment]
That makes absolutely sense! I will try as you described and keep you posted how it goes!

Thanks a lot!

**Comment by Wildstrubu** [comment]
Hi @callumparr 

You are correct that the normal walkthrough should work as all U are modified and the purpose is to read the modified U as canonical U.

I struggle always with the get_refs_from_sam.py is always blank, which I dont understand. The reference RNA is flipped to 3' to 5'. Is something wrong with my input bam file?

guppy_basecaller -i ~/fast5/ --config rna_r9.4.1_70bps_hac.cfg --reverse_sequence 1 --u_substitution 1 --min_qscore 7 
minimap2 -ax map-ont -t 8 ~/RNA_reference.fasta ~/guppy/*.fastq | samtools sort -o reads.sorted.bam -T reads.tmp
get_refs_from_sam.py ~/RNA_reference.fasta ~/reads.sorted.bam --output ~/reads.references.fasta --reverse 

Thanks for your inputs!

**Comment by callumparr** [comment]
Guppy with RNA config will reverse the sequence by default and will also substitute T > U by default as well. May save you a seconds typing. 

Just for clarification because was a little unsure from what you wrote. The input for minimap2 should be the standard FASTQ you'd normally use (i.e. 5' -> 3' in respect to the genome/transcriptome reference). The `get_refs_from_sam.py` will then match read ID with the reference sequence and also flip it from the normal 5' -> to 3' to 3' -> 5' that is required for the `prepare_mapped_reads.py`

What kind of reference are you using? Do you see any mapped reads? or just the `*` in the matches. Even with 100% replacement, I could at least get 30 ~ 40% of 'passed' reads mappable to a custom transcriptome I provided. 

Here is one of the BAM files I have for example with a few lines. It includes reads unable to be mapped. 

command was 

```
@PG     ID:minimap2     PN:minimap2     VN:2.16-r922    CL:minimap2 -t 8 -2 -ax map-ont -I 16G -uf --secondary=no Documents/multi_reads/IVT_minus_polyA.fasta Documents/multi_reads/taiyaki_input/190417_5EU_modified_RNA/190417_5EU_mo

```

```
97cc7475-4359-4a32-ad49-59f706b352c4    0       IVT_ALKBH5      168     60      99S22M2D1M2D10M1D3M1D2M2D5M1I4M3D2M2D28M3I15M2I13M1I3M1I6M1I4M3D55M3D21M1I1M2D12M1I26M1D2M1D8M2I2M1D20M2I3M1I13M1I11M1D1M1D11M1D4M1I6M1D14M1I4M1I5M1D3M
0c70109f-3014-4a48-8c1b-ba6a6dd3b0b1    0       IVT_ALKBH5      117     51      62S29M1D11M1I2M2D3M2D20M1I3M2D1M1D7M2D7M3I8M1D14M1I20M1I7M1D4M1D11M1I2M2D5M1I2M3D5M2D1M1D7M3I19M1D12M1I1M2I27M1D14M1I15M1D4M1D17M1I15M2I16M4D5M2I13M1I9
c5a2d0a8-abc3-44e3-aaf5-a913f0088b07    0       IVT_ALKBH5      117     57      70S22M1D4M1D3M1I10M3I1M1D2M3D21M1D3M2D1M2D13M1D11M1D32M4I5M2I19M1I3M2D13M1D3M3D29M1I41M2I30M1D18M1I28M1D7M1I4M1I12M1I25M1D4M1I2M1I5M2I16M1D9M1I16M1D5M1
9830c133-c960-4ff3-8151-e5ba4d9fa0d8    0       IVT_ALKBH5      42      49      20M3D25M4D4M1D11M3D3M2D6M3D6M1I9M1I6M1I10M1I5M1D20M2D7M2I11M1I3M2D41M1I4M2D2M3I16M1I12M1D6M2D3M1D55M1I11M3I17M1D6M3D10M1D4M2I13M1D19M3D18M1I2M1I10M1D12
73afc69e-e88a-4c3e-afe4-9f7e3ff7ecfb    0       IVT_ALKBH5      172     35      127S13M4D5M1I30M2D19M1I8M1I5M2I19M2D2M1I14M1D5M3I4M1D6M1D26M1I17M1I11M1D2M2D4M1D20M1D4M1D54M1I3M1I2M3I11M1I3M1I5M1D6M1D14M1I11M3I20M3D11M2I3M1D10M1D10M
a20077aa-fce1-418c-bbe1-ebbc961952c7    0       IVT_ALKBH5      168     58      112S22M2I44M1D6M1I17M1I6M1D7M1D4M1D8M1D10M4D32M1I12M1D9M1I23M2D15M1D6M1I14M1I2M1D29M5D6M1D7M3I6M1I9M1I6M1D37M2D13M1D7M1D17M1I8M1I10M1I5M2D9M4D8M8I8M3I2
74cbec58-8464-4450-a3ba-77ee3c5e92dd    0       IVT_ALKBH5      613     29      34S9M1I3M1I2M2D6M1D25M2I5M2D5M2D25M1I12M1D14M2D5M2D7M1D19M2D1M2D11M1D10M1D7M1I12M1I3M1D4M1D12M1D5M1I40M1D9M1I9M8I7M4I6M1D15M1D24M5I9M2D2M1I24M1I18M3I5M
e06c67bf-cbea-42fa-9381-fee81c8b98ba    0       IVT_ALKBH5      167     20      118S11M1I8M1D17M1I2M4D10M1D7M1D10M1D11M1I1M1I8M4I17M1D8M2D12M1D1M2I27M1I2M3D48M1D6M3D7M2I22M1I4M3D12M3D16M3I2M1I6M1I6M1I10M1I3M2I18M2D5M2I7M1I8M2D3M1I1
995edd5b-725b-49d1-8258-54ad54ba6840    0       IVT_ALKBH5      120     8       70S16M1D24M1D3M1D24M2D13M1I20M2I8M1I7M1I10M1D7M2I8M1I5M3I6M1I9M1I3M1I11M1I33M2D2M3D11M1I6M3I19M1D5M2I6M2D31M1I28M1D3M2I7M2I21M3I8M4I3M1D10M1I21M1D3M1I9
d6d92aea-229a-4fae-b777-f315ccb9e324    0       IVT_ALKBH5      113     2       63S4M1I22M1D7M1I4M2D3M1I5M1D21M4D4M5I9M2D4M1I14M1D8M2I10M1D7M1I3M1D7M2I6M1D12M1I8M2I4M1I12M1D25M3I2M1D1M2D24M1D11M1I6M2I2M1I7M1D2M1I12M3I3M1D8M1D5M1I2M
448ffc64-86bb-4eb6-9d1a-7f683096635a    4       *       0       0       *       *       0       0       ACTTAACCTGAGCCCTAACATTGAACAGATTGAACTCAAAAAGAACACCCTTCAGAAATCAGAAGCGAGGGGCCCGGGCTGAAGGAGAACGTCCTGTCCACACCGTACATCAGCTCCCCGAAAAGAA
19e38287-d98e-4c30-aa9d-8d18c976fa84    4       *       0       0       *       *       0       0       AAACACTCCTCCCATTTAACCTGAGCTCCAACACATAACTAGATTGAACAAAAAGAACACATCCTCTAGAAATCAGAGCGAGGGCACCTAGGCTGGGAAGGAGAATGCTCAGCACACATCAGCATTA
6bbf5b3a-a7a7-4f74-bc59-45cfbe286a19    0       IVT_ALKBH5      106     60      49S12M1I21M4I5M2D13M3I3M1I3M3D7M1I9M2I9M1D11M1D21M1I23M1D7M1D4M2D14M2D17M3D20M1I30M2D3M4D7M1I15M1D14M1D9M1D13M1I10M1I3M1I12M1D3M1I23M1I9M2I7M2I3M2D9M1I
af1ffab6-d9f2-4e83-94cf-0d6a0a79cf31    0       IVT_ALKBH5      118     1       75S16M1D9M1D13M1I6M3D16M4D4M1D2M1I26M1D6M1I32M1I5M2I10M1I3M1D4M3D2M2D8M1D48M2D15M2D11M1D5M1I13M1D6M1D16M1D9M2D1M2D1M1D19M1I2M1I16M1I8M1D7M1I13M1D12M2I8
915819b7-3304-4c25-a831-52373c837c3d    0       IVT_ALKBH5      201     1       133S11M1D7M1D12M2I31M5I1M2I8M1D3M1I9M1D11M1D1M1D5M2I21M1I5M2D5M1I2M1D15M1D5M1D3M1D14M3D1M1I9M2D19M2D16M1I5M1D20M2D11M1I4M1I6M1I5M1D1M1D20M1I24M1I6M1D21
cc078043-229e-4e2a-a38a-c38c740feb0c    4       *       0       0       *       *       0       0       CGTGACAAGACTGCTGGAACGTGGGCCAGGACTACACTGCCAATATCCTCTTGGAGCCATCTACCCATCGAGCACTTTCCCAAGGCAGCCCCTACCACGGGGACTACCCCCACCAGGGCCACGTACC
40b56031-92a7-467e-95d2-3aa7ab2b5dc7    4       *       0       0       *       *       0       0       CAGCCAGGACGAGCGCGCCAGAACCGAGGCCCATCTGACGGGTGGCGCCCGCGCTGAGAAGGGCCCGGCAACGAGCACACTGTGGACATGGGCCCCTGCGCAACAAGATCCCACTGCGAAGGCCATA
eb795138-e3e0-4ee0-8899-b99d58eec89a    4       *       0       0       *       *       0       0       ACAAAGCAGCCTACAGCTTTCCCGGTCGTCTTTAGTGGATCTCATAAAGAGGTCCCCTGCCACCCATCCCTCAACAGCCCTGCTCTAGTGGCATCAATATAGAAGCATCAGCAGCCGGAAGGCTCCT
1d59f2ee-e36c-4b53-b266-14f09ac4151d    4       *       0       0       *       *       0       0       AGGCATGAGCACAGGAGAACACCCCAGAAATGCATTGCTACAGCCATAAGGAACAATTCTGCCGAAAAACACCGCCTCGAGGTCGGGCCTCAGTGCTGGATTCCTGGTGCTTGGAACCAAGAGGAAG
43b7f273-125a-425f-9508-114ac4d6ef09    4       *       0       0       *       *       0       0       GAGAGAAAGAAGAAGTGGATAGAAATTGGACTTCGAATACCGTTCACTTGCTTCTTCTTCTTCTTTTTTTTCCTGGACTTACAAGGACGATGGTTGTTTGACCCCCGTGATGTGCTAGGCTGTATGT
bebb6d3f-f3b0-435b-9ea4-a64ec4fe7916    4       *       0       0       *       *       0       0       GGGACGATTCTCGCAGCGTATCCTTATGCGAGCACTTTCAAACGTGGACGGTGGCGCTGCAAGGGAGCGGCTGCTCTCTGCCCCCGCTGAACAAGTTGCTGGAACGCTGGCCATCCAGGAACACTGC
6630e873-2bd5-4111-a625-252a377c6721    4       *       0       0       *       *       0       0       CTCCCCCTCATCGACGTGCCTGCATATCCCGAACCAGACATTCATCGTCCGTACAAAAAGCAGGCCCTTTCCTTGGGAACCATCAGCCGCCCGGCGGCCGCCAGCGGCATCACGGACCCCCGCGCTG
128adcb3-0ac1-46e0-a6ef-04ba6154b3dd    4       *       0       0       *       *       0       0       GACCCTGGCAAAGCGACCATCGAGGAGCAGCGGCTGCAGGAAGGGGAGGAGGCGCGCTGTGAAGGCGGCATCCGCCAGATGCGCCCCTCCCACAGCCAGGATGAGCGCCAAGAACCGAGGCCCGTCT
dafd69ab-4cf1-4555-88e8-3a7f42c32ed4    4       *       0       0       *       *       0       0       TGGACGTCATGGACAACCCTGGGCAGGGTCCGCTGATGTGATGGCTGACCTCTCCCCGGGAACCACTTGGAAACCCTGCCCCACCATGGGACCCTGACAGACTGTCGAGACCGCGCAGGGCTCAAAC
3c237095-da6c-4d22-a13d-263a4f1a6172    0 

```

I remembered to additional things I did. 

1. 

I noticed from my in vitro transcription reaction there were lots of small read fragments. I think this quite common within _in vitro_ transcription, there are lots of false starts from the T7 promoter.  I did not want these reads so I filtered them out using `NanoFilt` using a minimum basecall length. I followed this by then filtering out these reads from my raw fast5 data using `fast5_fetcher` (at the time these had to be in single fast5 files rather than multi_fast5 I think this is still the case, not sure). At the same time, I also filtered the fast5 files that were mapped in the initial mapping from guppy step. I think this step is unnecessary but just to make it cleaner. 

1. Additionally, during the mapping, I used a transcriptome without poly-A tails. I think ultimately this makes no difference as these are usually not mapped anyway because guppy still does a poor job of basecalling this part of the read won't align whatever.  Again in my head, this seemed cleaner but I have no idea. 

I still unsure how taiyaki and guppy deals with poly-A tails or if direct RNA sequencing just ignores this and you still have to use tools like nanopolish to go into the raw data.

**Comment by Wildstrubu** [comment]
Thanks for the feedback.

For the reference I use the RNA (1.4kb, tried both 5'to3' and 3'to5'). The reference has a polyA.

The minimap2 seems to work. Just an example of my output:

PG     ID:minimap2     PN:minimap2     VN:2.17-r941    CL:minimap2 -ax splice -uf -k14 --secondary=no /Sequencing/References/RNA.fasta /guppy_firstround/subsampling/pass.fastq
719640bb-b4b2-4a8c-9543-348ff0f5d3b2    4       *       0       0       *       *       0       0       TACGCTACTACCTA....etc

The sequences in the minimap2 output are up to 1.4kb long. So that seems to work. But when I do "get_refs_from_sam.py" as describe in the box above, I get:

>eb708d03-19f6-493a-bf23-154c36aac378
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>f5dece0f-baac-444c-94df-5b5e913d035e
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>139a9a7b-6f44-4b5d-af85-c39ab2454561
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

etc...

**Comment by callumparr** [comment]
hmmm that's weird. Not sure why you are getting undetermined bases in the end. 

You definitely do not need to reverse the reference though. The reference file stays static throughout, the get_refs_from_sam.py will reverse the ground truth sequence for each read (this sequence is lifted from the reference file to where your read maps). What is your reference? 

It's a bit difficult to tell from the line of the SAM/BAM if this is working. You can run `samtools stats` to see the overall summary of mapping statistics. I haven't used the script since August last year so maybe there is something weird happening. Better to raise an issue specific to the Ns being output.

**Comment by tmassingham-ont** [comment]
Hello @Wildstrubu .  Are the sequences in your reference file lower case?  There is a  misbehaviour release of Taiyaki that causes lowercase bases to be mapped to ambiguity characters, which could explain what you are seeing.

@callumparr many thanks for the excellent help you've been giving so far.

**Comment by Wildstrubu** [comment]
Yes, the reference file had lower case. Now its working :) That simple, cant believe it. I am new to this type of analysis and thought that I miss something more substantial, but its in the details...

Thanks @callumparr for your insightful inputs, learned a lot!

@tmassingham-ont maybe if I can double check that my reference file is correct.

Reference file:
- upper case letters :)
- Type: RNA
- Orientation: 5' to 3'
- T/U should not make a difference (?)
- Since all U are modified, should they stay as U or need they to be converted to Y (for example) to tell taiyaki that this type of nucleotide are modified?

Thanks!

**Comment by tmassingham-ont** [comment]
The upper / lower case issue is our fault and this shouldn't be this fiddly, sorry.  The issue was found and fixed internally a while ago, but a fix has yet to be pushed to the external release.

Re: reference file.  Taiyaki is fine with an `--alphabet ACGU` but it might be easier to stick with `ACGT` (particularly if you are mapping using a model which has this alphabet).

Since all U's are modified in you sample, you should change them to a different letter to reflect this and inform Tiayaki about the modification, e.g.  `--mod Y T psiU`

**Comment by Wildstrubu** [comment]
Hi @callumparr and @tmassingham-ont,

The training as described by you two has worked very nicely! When running qualimap, the mapping quality is around 52, which I think is great!

Interestingly, the first ~100nt after the polyA-tail show low mapping (not many reads) compared to the rest of the mRNA (IVT mRNA). Is this something that you have experienced as well and do you know how I could improve that?

Also, when running this newly trained model for other IVT mRNAs, it seems not to work that well, although its the same modification. Is that something to be expected? I will train a new model specific for those reads and see how it performs.

Thanks again for all your inputs, very helpful!

**Comment by callumparr** [comment]
> Hi @callumparr and @tmassingham-ont,
> 
> The training as described by you two has worked very nicely! When running qualimap, the mapping quality is around 52, which I think is great!
> 
> Interestingly, the first ~100nt after the polyA-tail show low mapping (not many reads) compared to the rest of the mRNA (IVT mRNA). Is this something that you have experienced as well and do you know how I could improve that?
> 
> Also, when running this newly trained model for other IVT mRNAs, it seems not to work that well, although its the same modification. Is that something to be expected? I will train a new model specifically for those reads and see how it performs.
> 
> Thanks again for all your inputs, very helpful!

Not sure about the low mapping. What is defined as 100nt after polyA. I'm pretty sure you won't see polyA stretches in your basecalls. Guppy/taiyaki cannot deal with long stretches such as poly-A tails and that's why you need tools like nanopolish or tailfindr to call them independent of base-calling. The poly-A usually comes out as a string of GTs according to what I saw on nanopore community 

If you trained the model with only a few genes/sequences you would expect the model to poorly basecall divergent sequences. As calling nucleotide from its signal is greatly influenced by the signal of the neighbouring nucleotides you need a lot of variant signals to get a good model. Say if you trained it with one gene. It is obviously going to be biased by the signals from the specific sequences of that gene. 

What did you use to train? 

You are better to generate a cDNA library with T7 promoter for IVT to generate a more generalizable model.

**Comment by Wildstrubu** [comment]
The mapping is poor for around 100 nt towards to 5'end directly after the polyA tail. I don't intend to solve polyA resolution, its more about the sequence directly following the the polyA (i.e. upstream).

**Comment by callumparr** [comment]
How are you defining the poly-A tail then? 100nt towards the 5' end is after roughly 100nt from the very 3' end of base called read? Or is genome browser you see lots of error in the 3' end of alignment?

**Comment by Wildstrubu** [comment]
[low_coverage_towards_polyA.pdf](https://github.com/nanoporetech/taiyaki/files/4853252/low_coverage_towards_polyA.pdf)

Hope attached screenshot from IGV helps to better explain my concern. The polyA tail is around 50-60nt (indicated in green). 5'upstream from the polyA, you can see in red, that the reads are lower for approx. 100 nt and then the read coverage is perfect almost towards the very 5' end.  So, I wonder what causes that first drop? 

I like your idea with the de novo for identifying unexpected sequences, but otherwise I am pretty confident that the reference sequence is correct. I can create the same RNA, but without the modification to see, whether its due to the training or rather sequences based. Thanks for the links to the paper, will review that one.

**Comment by callumparr** [comment]
Ah OK. I see something similar but much shorter 10 - 40 nt. I am sure this is just an issue of interference from polyA signal. Maybe its good to ask on nanopore community. They may have a better idea.
