### ISSUE TITLE
train using PCR fragments

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/taiyaki#55]
Dear Developper,
i have few PCR products sequenced via Nanopore. however, guppy base calling is not very good. I would like to make a new model. Is it possible using sequences of PCR fragments and taiyaki?

Cheers
Luigi

**Comment by myrtlecat** [comment]
Hi Luigi.

I'm afraid the short answer is probably no, but it depends how many PCR products you have. Our usual guideline is that a training set should contain at the very least 1 megabase of unique sequence, e.g. 1000 distinct PCR products each 1kb in length. Ideally though you would use much more data than this.

Even if you do train a model, there is no guarantee it will perform better than the models in guppy (which are trained using taiyaki, btw). If you are having issues with guppy I suggest asking on the community for advice.
