### ISSUE TITLE
Read qscore decreases after training and rebasecalling

### ISSUE THREAD

**Issue by hanyue36** [nanoporetech/taiyaki#56]
We generate high accuracy target sequence data on PrometION with live basecalling and try taiyaki to improve read accuray further. But after training and rebasecalling. we found the qscore decreases a little bit (shown as below) but the identity shows the oppsite. 
So do you think it is an appropriate way to evaluate the performance?

Qscore

  | Basecall | Basecall_new
-- | -- | --
Min. | 6.554 | 4.533
1st Qu. | 10.706 | 8.057
Median | 11.856 | 8.597
Mean | 11.575 | 8.413
3rd Qu. | 12.707 | 8.960
Max. | 16.446 | 10.910

Identity

  | Basecall | Basecall_new
-- | -- | --
Min. | 0.7302 | 0.7188
1st Qu. | 0.9348 | 0.9427
Median | 0.9511 | 0.9572
Mean | 0.9434 | 0.9505
3rd Qu. | 0.9611 | 0.9661
Max. | 1.0000 | 1.0000

**Comment by tmassingham-ont** [comment]
Hello and thanks for the feed back.  We find that the Q scores obtained directly from trained models tend to be miscalibrated, a common issue in base calling going right back to capillary sequencing and the classic Phred papers.  
Our released production models (Guppy) process the raw Q scores with calibration factors to ensure they are accurate, but these factors are model dependent.  We'll add a script to Taiyaki shortly to empirically determine factors for a Taiyaki-trained model, and update the documentation accordingly.

To evaluate model performance, I would always recommending looking at the accuracy of real reads when compared to a reference.  Preferably, those reads would be from a different run and sample than the training data.


Note: issues nanoporetech/flappie#41 &  #53 are connected.
