### ISSUE TITLE
Basecall.py takes a long time

### ISSUE THREAD

**Issue by weir12** [nanoporetech/taiyaki#57]
Hi:
When I use `basecall.py` to predict modification information of total sample(about 3.5 million reads).This process has been going on for more than a week and is still going on.The GPU being used is nvidia tesla p100 with 16GB RAM.Is there any way to speed up the process?

**Comment by weir12** [comment]
I found `guppy` to be very fast and able to output modification information to fast5 file.Very good!
But I have the following concerns:
1.
`/Analyses/Basecall_1D_001/BaseCalled_template/ModBaseProbs`
How to understand the following information?(This doesn't seem quite the same as` basecalls.hdf5`)
![image](https://user-images.githubusercontent.com/37523816/67401930-65bfe680-f5e2-11e9-9416-72ea1628c901.png)
2.
There seems to be a discrepancy between outputs of guppy and basecall.py
If the difference is not negligible,How can I avoid it?
If it doesn't matter, why?
3.
Attach my command line information:
guppy:
```
guppy_basecaller -i ./fast5_test \
-s ./gupppy_res --recursive --flowcell FLO-MIN106 \
--kit SQK-RNA001  --num_callers 4 --device cuda:1 \
--reverse_sequence yes --u_substitution yes --fast5_out -m ./model.json \
--chunk_size 12000
```
taiyaki:
```
basecall.py --alphabet  ACGU --reverse --chunk_size 12000 --recursive  --device 2 --modified_base_output ./taiyaki_res/basecalls.hdf5 \
./fast5_test  ./model_final.checkpoint > ./taiyaki_res/basecalls.fa
```

**Comment by weir12** [comment]
**Update**:Installing `cupy` and `cudnn` helps speed things up.

**Comment by duolinwang** [comment]
I have the same problem, have you figure it out?

**Comment by tmassingham-ont** [comment]
@duolinwang  Could you open a new issue describing your problem and the environment in which you are running Taiyaki please?
