### ISSUE TITLE
Access to the Guppy template_r9.4.1_450bps_hac.jsn model for further training

### ISSUE THREAD

**Issue by kedartatwawadi** [nanoporetech/taiyaki#59]
I found that the pretrained model provided in the walkthrough ([URL Link)](https://s3-eu-west-1.amazonaws.com/ont-research/taiyaki_walkthrough.tar.gz) performs slightly worse that the Guppy high accuracy model template_r9.4.1_450bps_hac.jsn. 

Is it possible to provide the Guppy model for further training? (Or is there a way to convert the .jsn file into a .checkpoint format to be used with taiyaki for further training?)

Thanks a lot!

**Comment by marcus1487** [comment]
The `taiyaki/bin/json_to_checkpoint.py` script should address your needs here. Please post if additional assistance is needed.

**Comment by kedartatwawadi** [comment]
Thanks a lot :)
