### ISSUE TITLE
strange output after guppy

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/taiyaki#6]
Dear Developer,
I get this output when i use the model in combination with guppy

@a2aad6bd-b374-473c-9ad0-ca8649a28be8 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=557 ch=440 start_time=2018-09-27T08:41:06Z
AGT
+
""#
@e08fc779-d143-4dd8-837e-dd9e1183df11 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=579 ch=77 start_time=2018-09-27T08:46:35Z
AGT
+
""#
@bda5f326-e22c-4f99-a430-cecbf7d39bb6 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=621 ch=502 start_time=2018-09-27T08:45:31Z
AGT
+
""#
@cc6df394-873f-48e3-afb8-3410671bdb85 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=576 ch=293 start_time=2018-09-27T08:44:59Z
AGT
+
""#
@ac90af7a-a3e7-446e-aac2-83eb971fe4b5 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=554 ch=12 start_time=2018-09-27T08:41:39Z
AGT
+
""#
@3263edd2-8a2f-4930-9aef-4e7b80940fb4 runid=58f015113b3e17c33f219e761f9ef6172868dd8a sampleid=ale8 read=570 ch=293 start_time=2018-09-27T08:44:32Z
AGT
+
""#

Cheers
Luigi

**Comment by tmassingham-ont** [comment]
Would you be able to share some details of what you have done, please?

**Comment by lfaino** [comment]
Hi,
I re run the software and now it works.

Cheers
Luigi
