### ISSUE TITLE
Compatibility with Promethion/Modified Bases

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/taiyaki#61]
Hi there,

I couldn't find any documentation on this, but is Taiyaki compatible with Promethion models for training modified bases? As far as I know the base modbases cfg file for guppy only works with minION flow cells.

**Comment by myrtlecat** [comment]
Taiyaki is certainly compatible with promethion data, and there is no special configuration needed to train a promethion model.

The information needed to produce the mod-base output is contained in the model file itself, not the config file. So you probably want to use the promethion config file but override the default model. Apart from pointing to different models, most of the differences between minion and promethion configs are to do with making use of the extra compute power of the promethion.

To change the model file that guppy uses, you have a couple of options:

1. Call guppy as normal, but use the `--model_file` argument to override the default model file.
2. Make a new guppy config file (e.g. copy the promethion config). In this new config file, you should change the `model_file` line to point to your mod-base model. Then call guppy with the `--config` argument to override the default configuration.

In either case, I think you will need the `--fast5_out` option tell guppy to write mod-base output back to the fast5 files. See also the [readme section](https://github.com/nanoporetech/taiyaki#guppy-compatibility) on how to convert taiyaki's `.checkpoint` model files into json files that can be used with guppy.

If you need more help with the configuration then please get in touch again closer to the time. I'm not one of the devs working on guppy but I can put you in touch with the right people ;-)
