### ISSUE TITLE
Custom network can not run on guppy?

### ISSUE THREAD

**Issue by d05943006** [nanoporetech/taiyaki#65]
Hi:
I've run the workflow and successfully able to train the model **mGru_flipflop.py** 
When I try to build a simple custom model, the workflow is still able to run the **train_flipflop.py** and thus dump the JSON file.
However, when I try to run the model.json on guppy for evaluation, an error occurs.
It shows that the MatView sizes don't match. (See the attached figure below for models and error message reference)
![image](https://user-images.githubusercontent.com/22384763/71325045-19c9e900-2522-11ea-90ce-22df8de2afae.png)
![image](https://user-images.githubusercontent.com/22384763/71325049-25b5ab00-2522-11ea-8ece-91ea764305cb.png)
![image](https://user-images.githubusercontent.com/22384763/71325038-f9019380-2521-11ea-9e7f-bc50e8adf643.png)
Any idea?

BTW, if I try to conduct a custom model for guppy, how can I find the support layer list and protocol for guppy?
![image](https://user-images.githubusercontent.com/22384763/71325041-04ed5580-2522-11ea-974c-f84f4b83eb12.png)
Thank you very much!

**Comment by tmassingham-ont** [comment]
Hello.    Does the `basecall.py` script in Taiyaki work for you?

Not all network architectures that Taiyaki can train are supported by Guppy out-of-the-box.  Some layers may not be implemented, some may only support specific sizes that specified at compilation time -- this probably the issue with the GRU layer with different input & output sizes.  Your first two architectures look like fairly simple changes from the default model, so there may be an issue with theLSTM JSON output and I'll investigate in the New Year.

To get a list of Guppy supported layers, the best place to ask will be the Guppy Devs on the Nanopore Community wiki.

**Comment by d05943006** [comment]
Thank you for your reply! I'll try it on the `basecall.py`. Good luck with solving the LSTM issue. Happy new year!

**Comment by marcus1487** [comment]
LSTM layer is now supported in guppy >= 3.5.1.
