### ISSUE TITLE
Support for R 10.3

### ISSUE THREAD

**Issue by Serka-M** [nanoporetech/taiyaki#67]
Hi,
Taiyaki has been working great for modified base training with R 9.4.1 data.
However, with the arrival of R 10.3, I was wondering if you will release pre-trained models for the new flow cells?
Thanks!

**Comment by tmassingham-ont** [comment]
Hello.  I'm looking into releasing a full suite of models for Taiyaki, but, unfortunately, can't give an expected date of release yet.

**Comment by Serka-M** [comment]
Thanks for you answer. Still glad to hear that you are continuing the support for the software.
