### ISSUE TITLE
--fastq output throws numpy error

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#69]
I rerun basecall.py since the update of taiyaki to output fastq output. I tried this just on some test data include in taiyaki repository and using the flipflop remap model_checkpoint file. This throws an area relating to tensor and numpy. I have little idea of how to go about fixing. 

`
(taiyaki) (base) callum@dgt-gpu1:~$ basecall.py --device cuda:0 --fastq taiyaki/test/data/reads/0f776a08-1101-41d4-8097-89136494a46e.fast5 taiyaki/models/mGru_flipflop_remapping_model_r9_DNA.checkpoint > basecalls.fastq
* Loading model.
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'taiyaki.layers.Serial' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'taiyaki.layers.Convolution' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.padding.ConstantPad1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'taiyaki.layers.Reverse' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'taiyaki.layers.GruMod' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.GRU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'taiyaki.layers.GlobalNormFlipFlop' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
* Initializing reads file search.
* Found 1 reads.
* Calling reads.
Traceback (most recent call last):
  File "/usr/local/src/taiyaki/venv/bin/basecall.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/usr/local/src/taiyaki/bin/basecall.py", line 271, in <module>
    main()
  File "/usr/local/src/taiyaki/bin/basecall.py", line 245, in main
    args.fastq, args.qscore_scale, args.qscore_offset)
  File "/usr/local/src/taiyaki/bin/basecall.py", line 159, in process_read
    qscore_offset)
  File "/usr/local/src/taiyaki/taiyaki/qscores.py", line 153, in path_errprobs_to_qstring
    return qchar_from_errprob(filtered_probs, qscore_scale, qscore_offset)
  File "/usr/local/src/taiyaki/taiyaki/qscores.py", line 44, in qchar_from_errprob
    qscore = qscore_scale * qscore_from_errprob(errprob) + qscore_offset
  File "/usr/local/src/taiyaki/taiyaki/qscores.py", line 31, in qscore_from_errprob
    return -10.0 * np.log10(errprob)
  File "/usr/local/src/taiyaki/venv/lib/python3.5/site-packages/torch/tensor.py", line 412, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
`

**Comment by aevansNP** [comment]
Hi - thanks for raising this.

The error is raised when basecalling to fastq on the GPU, and was missed by our automatic tests, which only test CPU operation.

There is an easy fix, but it will take a little time for the changes to go through our system and get onto Github. In the meantime, if you want to get on with your work, there are two alternatives:

1) Use the CPU instead - this is slower, but if you don't have a lot of data then it may not matter.

2) Edit the file taiyaki/qscores.py so that the body of the function path_errorprobs_to_qstring() reads [from line 152]:

<pre>

    filtered_probs = errprobs[1:][path[1:]!=path[:-1]]
    if type(filtered_probs) == torch.Tensor:
        filtered_probs = filtered_probs.detach().cpu().numpy()
    return qchar_from_errprob(filtered_probs, qscore_scale, qscore_offset)

</pre>

(That is insert the two middle lines above).

**Comment by callumparr** [comment]
Thank you, the change in qscore.py file worked for my local install. I will wait for the fix and then ask local sys.admin to pull later.
