### ISSUE TITLE
taiyaki useful to try yet?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/taiyaki#7]
Is taiyaki as of today (2-Apr-2019) in a state that can be tried with a dataset to generate a new model and then apply the model to basecall a second dataset?

Should we wait for an imminent release that brings needed features to the fore?

**Comment by tmassingham-ont** [comment]
Taiyaki was released in a state that can train a model from one set of data and, provided that is compatible with Guppy, base call a second set of data.  The details of how to do this are in the documentation; if you require further help, please create an issue.
