### ISSUE TITLE
Where to get "pretrained" model?

### ISSUE THREAD

**Issue by sequinstandards** [nanoporetech/taiyaki#72]
In the walkthrough "r941_dna_minion.checkpoint" was given, but if I was using my own training data set, where would I get/create this file? The documentation doesn't specify how this file was generated in the first place.

**Comment by tmassingham-ont** [comment]
Hello.  They are contained in the `taiyaki_walkthrough.tar.gz` linked in the walk-through, just download this file (its about 10G).  If you don't want to download all this data, and just want the `r941_dna_minion.checkpoint` file, I can send you it directly.
