### ISSUE TITLE
R10 training models

### ISSUE THREAD

**Issue by nbeckloff** [nanoporetech/taiyaki#77]
Can a user train methylation models with Taiyaki using R10 data? Alternatively, do they need the Guppy methlyation mods to basecall the data they will need to train Taiyaki?

**Comment by nbeckloff** [comment]
Hi Tim,
   Thanks for the reply. A few follow-up questions if you can spare the time:


  1.  What file format would a user need for the reference sequence and model you mentioned below.
  2.  Do you have a potential timeline for the R10 mapping model?

Thanks in advance,
Nick

**Comment by cjfields** [comment]
Hi, we have a few projects that users want methylation base calling using R10 data and are also interested in this.  Any time frame for this?
