### ISSUE TITLE
Training RNA with pretained models

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#8]
How can we train model to work on modified RNA? The walkthroughs illustrate using pretrained models such as flip_flop but I think this is only used for calling DNA.

**Comment by tmassingham-ont** [comment]
Hello.  The process in the walk-through should be sufficient for standard DNA and RNA since a pre-trained RNA model is provided.  We will be adding functionality, including: support for training modifications, and the ability to train without starting from a pre-trained model.
