### ISSUE TITLE
sequence length for training

### ISSUE THREAD

**Issue by DeanH10** [nanoporetech/taiyaki#83]
Hi,
I have a question regarding the length of the input of a sequence into Taiyaki.
I am using Taiyaki to train Guppy and will have sequences of a different length some ranging into 30.000 bases. I wonder how the neural network is trained on sequences of this sizes as it is too long for RNNs (any type of RNN to my understanding as back propagation will vanish). Are the sequences cut at some point and if so at which length and how did you came to this solution?
Thank you in advance!

Cheers,
Dean

**Comment by tmassingham-ont** [comment]
Hello.   The preparation step for training, which maps the signal from each read to an appropriate reference, deals with whole reads.  The training process then samples batches of fixed-length chunks from these mappings, the chunk length varying between batches.  We've found that training with varying chunk lengths produces base calling models that generalize well to long reads providing the average chunk length is long enough.  
On the base calling side, the Guppy software cuts up reads into fixed-length chunks and then stitches the resulting sequences together.  The result of splitting then stitching has a similar accuracy to base callers, like https://github.com/nanoporetech/flappie, that deal with whole reads, but enables much higher performance to be achieved.
