### ISSUE TITLE
Restarting from a checkpoint

### ISSUE THREAD

**Issue by techsavy12** [nanoporetech/taiyaki#90]
Hello,
        I was wondering how to restart from a previous checkpoint. I was training a model but it stopped in between. It displayed the following error, which I have attached in the image below [Error: cost must be negative]. Your guidance would be really appreciated. Thank you

![error](https://user-images.githubusercontent.com/67298681/90830199-403d5f80-e30f-11ea-9ffb-d1561bcf529a.PNG)

**Comment by techsavy12** [comment]
Thank You for the response. I really appreciate your help. I am using a CPU so it tends to be slower. I tried restarting from the previous checkpoint with lr_max=2e-4 and I get the same error again. I am not confident in my model as I haven't tested it out yet, so I'm unsure whether I should disable the guard. Are there any other suggestions that you might recommend.

**Comment by tmassingham-ont** [comment]
Try disabling the guard.  Mathematically, all costs should be less than or equal to zero.  The offending value in your screen shot is 1.44e-03; close to zero and so probably rounding error rather than an indication that something is serious wrong -- the guard has been too sensitive.
