### ISSUE TITLE
Evaluation Method

### ISSUE THREAD

**Issue by techsavy12** [nanoporetech/taiyaki#91]
Hello,
	I am able to obtain basecall.hdf5 files from my newly trained model. I believe that this file provides the modified probability of each base of each reads. However, I was wondering if there are any method such as ROC or AUC curves available to evaluate my model.

**Comment by techsavy12** [comment]
I have been looking through megalodon but I'm unsure as to how we would input the output obtained from taiyaki into megalodon. Are there other evaluation methods available. Your help is very much appreciated. Thank You!

**Comment by marcus1487** [comment]
See relevant megalodon argument docs here (https://nanoporetech.github.io/megalodon/advanced_arguments.html#guppy-backend-argument) and here (https://nanoporetech.github.io/megalodon/advanced_arguments.html#taiyaki-backend-arguments). Also see the Taiyaki dump_json command to save a model to use with guppy (can use via megalodon with this output as well).  Megalodon provides the highest accuracy modified base calls and is thus the recommended method.
